-- MySQL Script generated by MySQL Workbench
-- sex 05 jan 2024 19:49:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema E.S.IdealBD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema E.S.IdealBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `E.S.IdealBD` ;
USE `E.S.IdealBD` ;

-- -----------------------------------------------------
-- Table `E.S.IdealBD`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E.S.IdealBD`.`Cliente` (
  `nif` VARCHAR(9) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `morada` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(12) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `notSMS` TINYINT NOT NULL,
  `notEmail` TINYINT NOT NULL,
  PRIMARY KEY (`nif`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E.S.IdealBD`.`Competencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E.S.IdealBD`.`Competencia` (
  `tipo` VARCHAR(10) NOT NULL,
  `nrCartao` INT NOT NULL,
  PRIMARY KEY (`nrCartao`),
  CONSTRAINT `fk_CompetenciaFuncionario_Funcionario1`
    FOREIGN KEY (`nrCartao`)
    REFERENCES `E.S.IdealBD`.`Funcionario` (`nrCartao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E.S.IdealBD`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E.S.IdealBD`.`Funcionario` (
  `nrCartao` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`nrCartao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E.S.IdealBD`.`PostoCombustao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E.S.IdealBD`.`PostoCombustao` (
  `nrPosto` INT NOT NULL,
  PRIMARY KEY (`nrPosto`),
  CONSTRAINT `fk_PostoCombustao_PostoTrabalho1`
    FOREIGN KEY (`nrPosto`)
    REFERENCES `E.S.IdealBD`.`PostoTrabalho` (`nrPosto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E.S.IdealBD`.`PostoEletrico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E.S.IdealBD`.`PostoEletrico` (
  `nrPosto` INT NOT NULL,
  PRIMARY KEY (`nrPosto`),
  CONSTRAINT `fk_PostoEletrico_PostoTrabalho1`
    FOREIGN KEY (`nrPosto`)
    REFERENCES `E.S.IdealBD`.`PostoTrabalho` (`nrPosto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E.S.IdealBD`.`PostoGasoleo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E.S.IdealBD`.`PostoGasoleo` (
  `nrPosto` INT NOT NULL,
  PRIMARY KEY (`nrPosto`),
  CONSTRAINT `fk_PostoGasoleo_PostoTrabalho1`
    FOREIGN KEY (`nrPosto`)
    REFERENCES `E.S.IdealBD`.`PostoTrabalho` (`nrPosto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E.S.IdealBD`.`PostoGasolina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E.S.IdealBD`.`PostoGasolina` (
  `nrPosto` INT NOT NULL,
  PRIMARY KEY (`nrPosto`),
  CONSTRAINT `fk_PostoGasolina_PostoTrabalho1`
    FOREIGN KEY (`nrPosto`)
    REFERENCES `E.S.IdealBD`.`PostoTrabalho` (`nrPosto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E.S.IdealBD`.`PostoHibrido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E.S.IdealBD`.`PostoHibrido` (
  `nrPosto` INT NOT NULL,
  PRIMARY KEY (`nrPosto`),
  CONSTRAINT `fk_PostoHibrido_PostoTrabalho1`
    FOREIGN KEY (`nrPosto`)
    REFERENCES `E.S.IdealBD`.`PostoTrabalho` (`nrPosto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E.S.IdealBD`.`PostoTrabalho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E.S.IdealBD`.`PostoTrabalho` (
  `nrPosto` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`nrPosto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E.S.IdealBD`.`PostoUniversal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E.S.IdealBD`.`PostoUniversal` (
  `nrPosto` INT NOT NULL,
  PRIMARY KEY (`nrPosto`),
  CONSTRAINT `fk_PostoUniversal_PostoTrabalho1`
    FOREIGN KEY (`nrPosto`)
    REFERENCES `E.S.IdealBD`.`PostoTrabalho` (`nrPosto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E.S.IdealBD`.`RegistoServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E.S.IdealBD`.`RegistoServico` (
  `nrTurno` INT NOT NULL,
  `nrMarcacao` INT NOT NULL,
  `inicio` DATETIME NOT NULL,
  `fim` DATETIME NOT NULL,
  PRIMARY KEY (`nrTurno`, `nrMarcacao`),
  INDEX `fk_RegistoServico_RegistoTurno1_idx` (`nrTurno` ASC) VISIBLE,
  CONSTRAINT `fk_RegistoServico_ServicoAgendado1`
    FOREIGN KEY (`nrMarcacao`)
    REFERENCES `E.S.IdealBD`.`ServicoAgendado` (`nrMarcacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RegistoServico_RegistoTurno1`
    FOREIGN KEY (`nrTurno`)
    REFERENCES `E.S.IdealBD`.`RegistoTurno` (`nrTurno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E.S.IdealBD`.`RegistoTurno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E.S.IdealBD`.`RegistoTurno` (
  `nrTurno` INT NOT NULL AUTO_INCREMENT,
  `nrCartaoFuncionario` INT NOT NULL,
  `inicio` DATETIME NOT NULL,
  `fim` DATETIME NOT NULL,
  PRIMARY KEY (`nrTurno`, `nrCartaoFuncionario`),
  INDEX `fk_RegistoTurno_Funcionario1_idx` (`nrCartaoFuncionario` ASC) VISIBLE,
  CONSTRAINT `fk_RegistoTurno_Funcionario1`
    FOREIGN KEY (`nrCartaoFuncionario`)
    REFERENCES `E.S.IdealBD`.`Funcionario` (`nrCartao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E.S.IdealBD`.`Servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E.S.IdealBD`.`Servico` (
  `idServico` INT NOT NULL AUTO_INCREMENT,
  `designacao` VARCHAR(45) NOT NULL,
  `tempoNecessario` INT NOT NULL,
  `tipo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idServico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E.S.IdealBD`.`ServicoAgendado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E.S.IdealBD`.`ServicoAgendado` (
  `nrMarcacao` INT NOT NULL AUTO_INCREMENT,
  `idServico` INT NOT NULL,
  `matricula` VARCHAR(6) NOT NULL,
  `nrCartaoFuncionario` INT NOT NULL,
  `tipo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`nrMarcacao`, `idServico`, `matricula`, `nrCartaoFuncionario`),
  INDEX `fk_ServicoAgendado_Veiculo1_idx` (`matricula` ASC) VISIBLE,
  INDEX `fk_ServicoAgendado_Servico1_idx` (`idServico` ASC) VISIBLE,
  INDEX `fk_ServicoAgendado_Funcionario1_idx` (`nrCartaoFuncionario` ASC) VISIBLE,
  CONSTRAINT `fk_ServicoAgendado_Veiculo1`
    FOREIGN KEY (`matricula`)
    REFERENCES `E.S.IdealBD`.`Veiculo` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ServicoAgendado_Servico1`
    FOREIGN KEY (`idServico`)
    REFERENCES `E.S.IdealBD`.`Servico` (`idServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ServicoAgendado_Funcionario1`
    FOREIGN KEY (`nrCartaoFuncionario`)
    REFERENCES `E.S.IdealBD`.`Funcionario` (`nrCartao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E.S.IdealBD`.`ServicoAgendadoIncompleto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E.S.IdealBD`.`ServicoAgendadoIncompleto` (
  `nrMarcacao` INT NOT NULL,
  `motivo` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`nrMarcacao`),
  CONSTRAINT `fk_ServicoAgendadoIncompleto_ServicoAgendado1`
    FOREIGN KEY (`nrMarcacao`)
    REFERENCES `E.S.IdealBD`.`ServicoAgendado` (`nrMarcacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E.S.IdealBD`.`ServicoCombustao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E.S.IdealBD`.`ServicoCombustao` (
  `idServico` INT NOT NULL,
  PRIMARY KEY (`idServico`),
  CONSTRAINT `fk_ServicoCombustao_Servico1`
    FOREIGN KEY (`idServico`)
    REFERENCES `E.S.IdealBD`.`Servico` (`idServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E.S.IdealBD`.`ServicoEletrico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E.S.IdealBD`.`ServicoEletrico` (
  `idServico` INT NOT NULL,
  PRIMARY KEY (`idServico`),
  CONSTRAINT `fk_ServicoEletrico_Servico1`
    FOREIGN KEY (`idServico`)
    REFERENCES `E.S.IdealBD`.`Servico` (`idServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E.S.IdealBD`.`ServicoGasoleo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E.S.IdealBD`.`ServicoGasoleo` (
  `idServico` INT NOT NULL,
  PRIMARY KEY (`idServico`),
  CONSTRAINT `fk_ServicoGasoleo_Servico1`
    FOREIGN KEY (`idServico`)
    REFERENCES `E.S.IdealBD`.`Servico` (`idServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E.S.IdealBD`.`ServicoGasolina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E.S.IdealBD`.`ServicoGasolina` (
  `idServico` INT NOT NULL,
  PRIMARY KEY (`idServico`),
  CONSTRAINT `fk_ServicoGasolina_Servico1`
    FOREIGN KEY (`idServico`)
    REFERENCES `E.S.IdealBD`.`Servico` (`idServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E.S.IdealBD`.`ServicoHibrido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E.S.IdealBD`.`ServicoHibrido` (
  `idServico` INT NOT NULL,
  PRIMARY KEY (`idServico`),
  CONSTRAINT `fk_ServicoHibrido_Servico1`
    FOREIGN KEY (`idServico`)
    REFERENCES `E.S.IdealBD`.`Servico` (`idServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E.S.IdealBD`.`ServicoUniversal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E.S.IdealBD`.`ServicoUniversal` (
  `idServico` INT NOT NULL,
  PRIMARY KEY (`idServico`),
  CONSTRAINT `fk_ServicoUniversal_Servico1`
    FOREIGN KEY (`idServico`)
    REFERENCES `E.S.IdealBD`.`Servico` (`idServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E.S.IdealBD`.`Veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E.S.IdealBD`.`Veiculo` (
  `matricula` VARCHAR(6) NOT NULL,
  `nifCliente` VARCHAR(9) NOT NULL,
  `tipo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`matricula`, `nifCliente`),
  INDEX `fk_Veiculo_Cliente_idx` (`nifCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Veiculo_Cliente`
    FOREIGN KEY (`nifCliente`)
    REFERENCES `E.S.IdealBD`.`Cliente` (`nif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E.S.IdealBD`.`VeiculoEletrico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E.S.IdealBD`.`VeiculoEletrico` (
  `matricula` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`matricula`),
  CONSTRAINT `fk_VeiculoEletrico_Veiculo1`
    FOREIGN KEY (`matricula`)
    REFERENCES `E.S.IdealBD`.`Veiculo` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E.S.IdealBD`.`VeiculoGasoleo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E.S.IdealBD`.`VeiculoGasoleo` (
  `matricula` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`matricula`),
  CONSTRAINT `fk_VeiculoGasoleo_Veiculo1`
    FOREIGN KEY (`matricula`)
    REFERENCES `E.S.IdealBD`.`Veiculo` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E.S.IdealBD`.`VeiculoGasolina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E.S.IdealBD`.`VeiculoGasolina` (
  `matricula` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`matricula`),
  CONSTRAINT `fk_VeiculoGasolina_Veiculo1`
    FOREIGN KEY (`matricula`)
    REFERENCES `E.S.IdealBD`.`Veiculo` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E.S.IdealBD`.`VeiculoHibrido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E.S.IdealBD`.`VeiculoHibrido` (
  `matricula` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`matricula`),
  CONSTRAINT `fk_VeiculoHibrido_Veiculo1`
    FOREIGN KEY (`matricula`)
    REFERENCES `E.S.IdealBD`.`Veiculo` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
